/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.*;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testQuotes() throws IOException {
        InputStream inputStream = getClass().getResourceAsStream("/recentquotes.json");
        Reader reader = new InputStreamReader(inputStream);

        Gson gson = new Gson();
        RecentQuotes[] quotes = gson.fromJson(reader, RecentQuotes[].class);


        assertTrue(quotes.length > 0, "There should be at least one quote");


        Random random = new Random();
        int randomIndex = random.nextInt(quotes.length);

        String randomQuote = quotes[randomIndex].getText();
        String randomAuthor = quotes[randomIndex].getAuthor();

        assertFalse(randomQuote.isEmpty(), "The random quote should not be empty");
        assertFalse(randomAuthor.isEmpty(), "The random author should not be empty");
        if (randomQuote.equals("")) {
            System.out.println("There is no quotes for this author");
        }
    }
    }

